
/*
export const REQUEST_INSURANCES = "REQUEST_INSURANCES"
export const ADD_INSURANCE = "ADD_INSURANCE"
export const UPDATE_INSURANCE = "UPDATE_INSURANCE"
export const DELETE_INSURANCE = "DELETE_INSURANCE"

export const REQUEST_PROVIDERS= "REQUEST_PROVIDERS"
export const ADD_PROVIDER = "ADD_PROVIDER"
export const UPDATE_PROVIDER = "UPDATE_PROVIDER"
export const DELETE_PROVIDER = "DELETE_PROVIDER"

export const REQUEST_BEHAVIORS = "REQUEST_BEHAVIORS"
export const CREATE_BEHAVIOR = "CREATE_BEHAVIORS"
export const UPDATE_BEHAVIOR = "UPDATE_BEHAVIORS"
export const DELETE_BEHAVIOR = "DELETE_BEHAVIOR"

export const REQUEST_CONDITIONS= "REQUEST_CONDITIONS"
export const ADD_CONDITION = "ADD_CONDITION"
export const UPDATE_CONDITION = "UPDATE_CONDITION"
export const DELETE_CONDITION = "DELETE_CONDITION"
*/
